<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Introduction à l’inférence statistique | Modélisation statistique</title>
  <meta name="description" content="Ces notes forment un complément web du cours MATH 60604 (Modélisation statistique) offert à la M.Sc. en gestion (science des données et analytique d’affaires) à HEC Montréal." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Introduction à l’inférence statistique | Modélisation statistique" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Ces notes forment un complément web du cours MATH 60604 (Modélisation statistique) offert à la M.Sc. en gestion (science des données et analytique d’affaires) à HEC Montréal." />
  <meta name="github-repo" content="lbelzile/math60604" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Introduction à l’inférence statistique | Modélisation statistique" />
  
  <meta name="twitter:description" content="Ces notes forment un complément web du cours MATH 60604 (Modélisation statistique) offert à la M.Sc. en gestion (science des données et analytique d’affaires) à HEC Montréal." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="regression-lineaire.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<link href="libs/rglwidgetClass-2/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-2/rglClass.src.js"></script>
<script src="libs/CanvasMatrix4-2016/CanvasMatrix.src.js"></script>
<script src="libs/rglWebGL-binding-0.100.54/rglWebGL.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modélisation statistique</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Remarques</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction à l’inférence statistique</a></li>
<li class="chapter" data-level="2" data-path="regression-lineaire.html"><a href="regression-lineaire.html"><i class="fa fa-check"></i><b>2</b> Régression linéaire</a></li>
<li class="chapter" data-level="3" data-path="vraisemblance.html"><a href="vraisemblance.html"><i class="fa fa-check"></i><b>3</b> Inférence basée sur la vraisemblance</a></li>
<li class="chapter" data-level="4" data-path="modeles-lineaires-generalises.html"><a href="modeles-lineaires-generalises.html"><i class="fa fa-check"></i><b>4</b> Modèles linéaires généralisés</a></li>
<li class="chapter" data-level="5" data-path="donnees-correlees-longitudinales.html"><a href="donnees-correlees-longitudinales.html"><i class="fa fa-check"></i><b>5</b> Données corrélées et longitudinales</a></li>
<li class="chapter" data-level="6" data-path="modeles-lineaires-mixtes.html"><a href="modeles-lineaires-mixtes.html"><i class="fa fa-check"></i><b>6</b> Modèles linéaires mixtes</a></li>
<li class="chapter" data-level="7" data-path="survie.html"><a href="survie.html"><i class="fa fa-check"></i><b>7</b> Analyse de survie</a></li>
<li class="appendix"><span><b>Annexe</b></span></li>
<li class="chapter" data-level="A" data-path="complement.html"><a href="complement.html"><i class="fa fa-check"></i><b>A</b> Compléments mathématiques</a></li>
<li class="chapter" data-level="B" data-path="math.html"><a href="math.html"><i class="fa fa-check"></i><b>B</b> Dérivations mathématiques</a></li>
<li><a href="r.html#r"><strong>R</strong></a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modélisation statistique</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Introduction à l’inférence statistique</h1>
<p>Ce chapitre porte sur deux concepts fondamentaux pour la modélisation, à savoir les principes sous-jacents aux tests d’hypothèses et l’analyse exploratoire des données.</p>
<!-- ## Prérequis -->
<!-- Bien que sans prérequis, nous assumerons que l'étudiant(e) a une connaissance préalable des notions suivantes: -->
<!-- - population et échantillon,  -->
<!-- - types de variables: continues, catégorielles (ordinales ou nominales), binaires,  -->
<!-- - variables aléatoires et leurs lois (Bernoulli, binomiale, géométrique, Poisson, normale, Student, exponentielle, Weibull, etc.),  -->
<!-- - propriétés de variables aléatoires: espérance, variance, biais,  -->
<!-- - graphiques de base (histogramme, nuage de point, densité, boîte à moustache, etc.),  -->
<!-- - théorème central limite, -->
<!-- - tests-$t$ pour un et deux échantillons et pour données appariées, -->
<!-- - régression linéaire simple. -->
<!-- Ces notions sont d'ordinaire traitées dans un cours d'introduction à la statistique au niveau baccalauréat/licence, voir même au collégial. -->
<p>L’inférence statistique a pour but de tirer des conclusions formelles à partir de données. Dans le cadre de la recherche scientifique, le chercheur formule une hypothèse, collecte des données et conclut quant à la plausibilité de son hypothèse.</p>
<p>On distingue deux types de jeux de données: les données <strong>expérimentales</strong> sont typiquement collectées en milieu contrôlé suivant un protocole d’enquête et un plan d’expérience: elles servent à répondre à une question prédéterminée. L’approche expérimentale est désirable pour éviter le «jardin des embranchements» (une <a href="http://www.stat.columbia.edu/~gelman/research/unpublished/p_hacking.pdf">allégorie signifiant qu’un chercheur peut raffiner son hypothèse à la lumière des données, sans ajustement pour des variables confondantes</a>), mais elle n’est pas toujours réalisable: par exemple, un économiste ne peut pas modifier les taux d’intérêts pour observer les impacts sur le taux d’épargne des consommateurs. Lorsque les données ont été collectées préalablement à d’autres fins, on parle de données <strong>observationnelles</strong>.</p>
<p>Par modèle, on entendra la spécification d’une loi aléatoire pour les données et une équation reliant les paramètres ou l’espérance conditionnelle d’une variable réponse <span class="math inline">\(Y\)</span> à un ensemble de variables explicatives <span class="math inline">\(\mathbf{X}\)</span>. Ce modèle peut servir à des fins de prédiction (modèle prédictif) ou pour tester des hypothèses de recherche concernant les effets de
ces variables (modèle explicatif). Ces deux objectifs ne sont pas mutuellement exclusifs même si on fait parfois une distinction entre inférence et prédiction.</p>
<p>Un modèle prédictif permet d’obtenir des prédictions de la valeur de <span class="math inline">\(Y\)</span> pour d’autres combinaisons de variables explicatives ou des données futures. Par exemple, on peut chercher à prédire la consommation énergétique d’une maison en fonction de la météo, du nombre d’habitants de la maison et de sa taille. La plupart des boîtes noires utilisées en apprentissage automatique tombent dans la catégorie des modèles prédictifs: ces modèles ne sont pas interprétables et ignorent parfois la structure inhérente aux données.</p>
<p>Par contraste, les modèles explicatifs sont souvent simples et interprétables; les modèles de régressions sont fréquemment utilisés pour l’inférence. On se concentrera dans ce cours sur les modèles explicatifs. Par exemple, on peut chercher à déterminer</p>
<ul>
<li>Est-ce que les consommateurs sont prêts à dépenser davantage lorsqu’ils paient par crédit qu’en argent comptant?</li>
<li>Est-ce qu’il y a de la discrimination salariale envers les femmes professeurs d’un collège américain?</li>
<li>Études supérieures: <a href="https://www.theglobeandmail.com/report-on-business/is-the-university-experience-worth-the-cost/article31703109/">est-ce que le prix en vaut la chandelle?</a>.</li>
<li>Quels sont les critères médicaux qui impactent les primes d’assurance maladies?</li>
<li>Qu’est-ce qui explique que les prix de l’essence soient plus élevés en Gaspésie qu’ailleurs au Québec? <a href="http://www.regie-energie.qc.ca/energie/rapports/Rapport_PrixGasp%C3%A9sie_20191219.pdf">Un rapport de surveillance des prix de l’essence en Gaspésie par la Régie de l’énergie se penche sur la question.</a></li>
<li>Est-ce que les examens pratiques de conduite sont plus faciles en régions en Grande-Bretagne? <a href="https://www.theguardian.com/world/2019/aug/23/an-easy-ride-scottish-village-fuels-debate-driving-test-pass-rates">Une analyse du journal britannique <em>The Guardian</em></a> laisse penser que c’est le cas.</li>
<li>Est-ce le risque de transmission de la Covid augmente en fonction de la distanciation? <a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31142-9/fulltext">Une (mauvaise) méta-analyse dit que oui</a> (ou l’art de tirer des conclusions erronées à partir d’une étude bancale).</li>
</ul>
<div id="tests" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Tests d’hypothèse</h2>
<p>Un test d’hypothèse statistique est une façon d’évaluer la preuve statistique provenant d’un échantillon afin de faire une décision quant à la population sous-jacente. Les étapes principales sont:</p>
<ul>
<li>définir les paramètres du modèles,</li>
<li>formuler les hypothèses alternatives et nulles,</li>
<li>choisir et calculer la statistique de test,</li>
<li>déterminer son comportement sous <span class="math inline">\(\mathscr{H}_0\)</span> (loi nulle),</li>
<li>calculer la valeur-<em>p</em>,</li>
<li>conclure dans le contexte du problème (rejeter ou ne pas rejeter <span class="math inline">\(\mathscr{H}_0\)</span>).</li>
</ul>
<p>Mon approche privilégiée pour présenter les tests d’hypothèse est de faire un parallèle avec un procès pour meurtre où vous êtes nommé juré.</p>
<ul>
<li>Le juge vous demande de choisir entre deux hypothèses mutuellement exclusives, coupable ou non-coupable, sur la base des preuves présentées.</li>
<li>Votre postulat de départ repose sur la présomption d’innocence: vous condamnerez uniquement le suspect si la preuve est accablante. Cela permet d’éviter les erreurs judiciaires. L’hypothèse nulle <span class="math inline">\(\mathscr{H}_0\)</span> est donc <em>non-coupable</em>, et l’hypothèse alternative <span class="math inline">\(\mathscr{H}_a\)</span> est coupable. En cas de doute raisonnable, vous émettrez un verdict de non-culpabilité.</li>
<li>La choix de la statistique de test représente la preuve. Plus la preuve est accablante, plus grande est la chance d’un verdict de culpabilité — le procureur a donc tout intérêt à bien choisir les faits présentés en cour. Le choix de la statistique devrait donc idéalement maximiser la preuve pour appuyer le postulat de culpabilité le mieux possible (ce choix reflète la <strong>puissance</strong> du test).</li>
<li>En qualité de juré, vous analysez la preuve à partir de la jurisprudence et de l’avis d’expert pour vous assurer que les faits ne relèvent pas du hasard. Pour le test d’hypothèse, ce rôle est tenu par la loi sous <span class="math inline">\(\mathscr{H}_0\)</span>: si la personne était innocente, est-ce que les preuves présentées tiendraient la route? des traces d’ADN auront davantage de poids que des ouï-dire (la pièce de théâtre <em>Douze hommes en colère</em> de Reginald Rose présente un bel exemple de procès où un des juré émet un doute raisonnable et convainc un à un les autres membres du jury de prononcer un verdict de non-culpabilité).</li>
<li>Vous émettez un verdict, à savoir une décision binaire, où l’accusé est déclaré soit non-coupable, soit coupable. Si vous avez une valeur-<em>p</em>, disons <span class="math inline">\(P\)</span>, pour votre statistique de test et que vous effectuez ce dernier à niveau <span class="math inline">\(\alpha\)</span>, la règle de décision revient à rejeter <span class="math inline">\(\mathscr{H}_0\)</span> si <span class="math inline">\(P &lt; \alpha\)</span>.</li>
</ul>
<p>On s’attarde davantage sur ces définitions heuristiques et le vocabulaire employé pour parler de tests d’hypothèse. Le matériel de la section suivante a été préparé par Juliana Schulz.</p>
<div id="hypothèse" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Hypothèse</h3>
<p>Dans les test statistique il y a toujours deux hypothèse: l’hypothèse nulle (<span class="math inline">\(\mathscr{H}_{0}\)</span>) et l’hypothèse alternative (<span class="math inline">\(\mathscr{H}_a\)</span>). Habituellement, l’hypothèse nulle est le « statu quo » et l’alternative est l’hypothèse que l’on cherche à démontrer. Un test d’hypothèse statistique nous permet de décider si nos données nous fournissent assez de preuves pour rejeter <span class="math inline">\(\mathscr{H}_0\)</span> en faveur de <span class="math inline">\(\mathscr{H}_a\)</span>, selon un risque d’erreur spécifié. Généralement, les tests d’hypothèses sont exprimés en fonction de paramètres (de valeurs inconnues) du modèle sous-jacent, par ex. <span class="math inline">\(\theta\)</span>. Un test d’hypothèse bilatéral concernant un paramètre unidimensionnel <span class="math inline">\(\theta\)</span> s’exprimerait la forme suivante:
<span class="math display">\[\begin{align*}
\mathscr{H}_0: \theta=\theta_0 \qquad \text{versus} \qquad \mathscr{H}_a:\theta \neq \theta_0.
\end{align*}\]</span>
Ces hypothèses permettent de tester si <span class="math inline">\(\theta\)</span> est égal à une valeur numérique précise <span class="math inline">\(\theta_0\)</span>.</p>
<p>Par exemple, pour un test bilatéral concernant le paramètre d’un modèle de régression <span class="math inline">\(\beta_j\)</span> associé à une variable explicative d’intérêt <span class="math inline">\(\mathrm{X}_j\)</span>, les hypothèses sont
<span class="math display">\[\begin{align*}
\mathscr{H}_0: \beta_j=\beta_j^0 \qquad \text{versus} \qquad \mathscr{H}_a:\beta_j \neq \beta_j^0, 
\end{align*}\]</span>
où <span class="math inline">\(\beta_j^0\)</span> est une valeur précise qui est reliée à la question de recherche. Par exemple, si <span class="math inline">\(\beta_j^0=0\)</span> la question de recherche sous-jacente est: est-ce que la covariable <span class="math inline">\(\mathrm{X}_j\)</span> impacte la variable réponse d’intérêt <span class="math inline">\(Y\)</span> une fois l’effet des autres variables pris en compte?</p>
<p>Remarque: il est possible d’imposer une direction dans les tests en considérant une hypothèse alternative de la forme <span class="math inline">\(\mathscr{H}_a: \theta &gt; \theta_0\)</span> ou <span class="math inline">\(\mathscr{H}_a: \theta &lt; \theta_0\)</span>.</p>
</div>
<div id="statistique-de-test" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Statistique de test</h3>
<p>Une statistique de test <span class="math inline">\(T\)</span> est un fonctionnel des données qui résume l’information contenue dans les données pour <span class="math inline">\(\theta\)</span>. La forme de la statistique de test est choisie de façon à ce que son comportement sous <span class="math inline">\(\mathscr{H}_0\)</span>, c’est-à-dire l’ensemble des valeurs que prend <span class="math inline">\(T\)</span> si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie et leur probabilité relative, soit connu. En effet, <span class="math inline">\(T\)</span> est une variable aléatoire et sa valeur va changer selon l’échantillon. La <strong>loi nulle</strong> de la statistique de test nous permet de déterminer quelles valeurs de <span class="math inline">\(T\)</span> sont plausibles si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie. Plusieurs statistiques que l’on couvrira dans ce cours sont des <strong>statistiques de Wald</strong>, de la forme
<span class="math display">\[\begin{align*}
T = \frac{\widehat{\theta} - \theta_0}{\mathrm{se}(\widehat{\theta})} 
\end{align*}\]</span>
où <span class="math inline">\(\widehat{\theta}\)</span> est l’estimateur du paramètre <span class="math inline">\(\theta\)</span>, <span class="math inline">\(\theta_0\)</span> la valeur numérique postulée (par ex., zéro) et <span class="math inline">\(\mathrm{se}(\widehat{\theta})\)</span> est l’estimateur de l’écart-type de <span class="math inline">\(\widehat{\theta}\)</span>.</p>
<p>Par exemple, pour une hypothèse sur la moyenne d’une population de la forme
<span class="math display">\[\begin{align*}
\mathscr{H}_0: \mu=0, \qquad  \mathscr{H}_a:\mu \neq 0, 
\end{align*}\]</span>
la statistique de test de Wald est
<span class="math display">\[\begin{align*}
T &amp;= \frac{\overline{X}-0}{S_n/\sqrt{n}}
\end{align*}\]</span>
où <span class="math inline">\(\overline{X}\)</span> est la moyenne de l’échantillon <span class="math inline">\(X_1, \ldots, X_n\)</span>,
<span class="math display">\[\begin{align*}
\overline{X} &amp;= \frac{1}{n} \sum_{i=1}^n X_i = \frac{X_1+ \cdots + X_n}{n}
\end{align*}\]</span>
et l’erreur-type de la moyenne <span class="math inline">\(\overline{X}\)</span> est <span class="math inline">\(S_n/\sqrt{n}\)</span>; l’écart-type <span class="math inline">\(S_n\)</span> est un estimateur de <span class="math inline">\(\sigma\)</span>, où
<span class="math display">\[\begin{align*}
S^2_n &amp;= \frac{1}{n-1} \sum_{i=1}^n (X_i-\overline{X})^2.
\end{align*}\]</span></p>
<p>Il convient de faire la différence entre procédures/formules et valeurs numériques. Un <strong>estimateur</strong> est une règle ou une formule utilisée pour calculer l’estimation d’un paramètre ou quantité d’intérêt selon des données observées. Par exemple, la moyenne d’échantillon <span class="math inline">\(\overline{X}\)</span> est un estimateur de la moyenne dans la population <span class="math inline">\(\mu\)</span>. Une fois qu’on a des données observées, on peut calculer un estimé de la moyenne empirique <span class="math inline">\(\overline{x},\)</span> c’est-à-dire, on obtient une valeur numérique. Autrement dit,</p>
<ul>
<li>un estimateur est une fonction de variables aléatoires et donc c’est aussi une variable aléatoire car sa valeur fluctue d’un échantillon à l’autre.</li>
<li>l’estimé est la valeur numérique calculée sur un échantillon donné.</li>
</ul>
</div>
<div id="loi-nulle-et-valeur-p" class="section level3" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Loi nulle et valeur-<em>p</em></h3>
<p>La <strong>valeur-<em>p</em></strong> nous permet de déterminer si la valeur observée de la statistique de test <span class="math inline">\(T\)</span> est plausible sous <span class="math inline">\(\mathscr{H}_0\)</span>. Plus précisément, la valeur-<em>p</em> est la probabilité, si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie, que la statistique de test soit égale or plus extrême à ce qu’on observe. Supposons qu’on a un échantillon <span class="math inline">\(X_1, \ldots, X_n\)</span> et qu’on observe une valeur de la statistique de test de <span class="math inline">\(T=t\)</span>. Pour un test d’hypothèse bilatéral <span class="math inline">\(\mathscr{H}_0:\theta=\theta_0\)</span> vs. <span class="math inline">\(\mathscr{H}_a:\theta \neq \theta_0\)</span>, la valeur-<em>p</em> est
<span class="math inline">\(\mathsf{Pr}_0(|T| \geq |t|)\)</span>. Si la distribution de <span class="math inline">\(T\)</span> est symétrique autour de zéro, la valeur-<em>p</em> vaut
<span class="math display">\[\begin{align*}
p = 2 \times \mathsf{Pr}_0(T \geq |t|).
\end{align*}\]</span></p>
<p>Prenons l’exemple d’un test d’hypothèse bilatéral pour la moyenne au population <span class="math inline">\(\mathscr{H}_0:\mu=0\)</span> contre <span class="math inline">\(\mathscr{H}_a:\mu \neq 0\)</span>. Si l’échantillon provient d’une (population de) loi normale <span class="math inline">\(\mathsf{No}(\mu, \sigma^2)\)</span>, on peut démontrer que, si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie et donc <span class="math inline">\(\mu=0\)</span>), la statistique de test
<span class="math display">\[\begin{align*}
T = \frac{\overline{X}}{S/\sqrt{n}}
\end{align*}\]</span>
suit une loi de Student-<span class="math inline">\(t\)</span> avec <span class="math inline">\(n-1\)</span> degrés de liberté, dénotée <span class="math inline">\(\mathsf{St}_{n-1}\)</span>. À partir de cette loi nulle, on peut calculer la valeur-<em>p</em> (ou bien à partir d’une table ou d’un logiciel statistique). Puisque la distribution Student-<span class="math inline">\(t\)</span> est symétrique autour de <span class="math inline">\(0\)</span>, on peut calculer la valeur-<em>p</em> comme <span class="math inline">\(P = 2\times\mathsf{Pr}(T &gt; |t|)\)</span>, où <span class="math inline">\(T \sim \sim \mathsf{St}_{n-1}\)</span>.</p>
</div>
<div id="conclusion" class="section level3" number="1.1.4">
<h3><span class="header-section-number">1.1.4</span> Conclusion</h3>
<p>La valeur-<em>p</em> nous permet de faire une décision quant aux hypothèses du test. Si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie, la valeur-<em>p</em> suit une loi uniforme. <a href="https://xkcd.com/1478/">Si la valeur-<em>p</em> est petite</a>, ça veut dire que le fait d’observer une statistique de test égal ou encore plus extrême que <span class="math inline">\(T=t\)</span> est peu probable, et donc nous aurons tendance de croire que <span class="math inline">\(\mathscr{H}_0\)</span> n’est pas vraie. Il y a pourtant toujours un risque sous-jacent de commettre un erreur quand on prend une décision. En statistique, il y a <a href="https://xkcd.com/2303/">deux types d’erreurs</a>:</p>
<ul>
<li>erreur de type I: on rejette <span class="math inline">\(\mathscr{H}_0\)</span> alors que <span class="math inline">\(\mathscr{H}_0\)</span> est vraie</li>
<li>erreur de type II: on ne rejette pas <span class="math inline">\(\mathscr{H}_0\)</span> alors que <span class="math inline">\(\mathscr{H}_0\)</span> est fausse</li>
</ul>
<p>Ces deux erreurs ne sont pas égales: on cherche souvent à contrôler l’erreur de type I (une erreur judiciaire, condamner un innocent). Pour se prémunir face à ce risque, on fixe préalablement un niveau de tolérance. Plus notre seuil de tolérance <span class="math inline">\(\alpha\)</span> est grand, plus on rejette souvent l’hypothèse nulle même si cette dernière est vraie.
La valeur de <span class="math inline">\(\alpha \in (0, 1)\)</span> est la probabilité qu’on rejette <span class="math inline">\(\mathscr{H}_0\)</span> quand <span class="math inline">\(\mathscr{H}_0\)</span> est en fait vraie.
<span class="math display">\[\begin{align*}
\alpha = \mathsf{Pr}_0\left(\text{ rejeter } \mathscr{H}_0\right).
\end{align*}\]</span>
Comme chercheur, on choisit ce niveau <span class="math inline">\(\alpha\)</span>; habituellement <span class="math inline">\(1\)</span>%, <span class="math inline">\(5\)</span>% ou <span class="math inline">\(10\)</span>%. La probabilité de commettre une erreur de type I est <span class="math inline">\(\alpha\)</span> seulement si le modèle nul postulé pour <span class="math inline">\(\mathscr{H}_0\)</span> est correctement spécifié (sic) et correspond au modèle générateur des données.</p>
<p>Le choix du statu quo (typiquement <span class="math inline">\(\mathscr{H}_0\)</span>) s’explique plus facilement avec un exemple médical. Si vous voulez prouver qu’un nouveau traitement est meilleur que l’actuel (ou l’absence de traitement), vous devez démontrer hors de tout doute raisonnable que ce dernier ne cause pas de torts aux patients et offre une nette amélioration (pensez à Didier Raoult et ses allégations non-étayées voulant que l’hydrochloroquine, un antipaludique, soit efficace face au virus de la Covid19).</p>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Décision</strong> \ <strong>vrai modèle</strong></th>
<th align="center"><span class="math inline">\(\mathscr{H}_0\)</span></th>
<th align="center"><span class="math inline">\(\mathscr{H}_a\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ne pas rejeter <span class="math inline">\(\mathscr{H}_0\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center">erreur de type II</td>
</tr>
<tr class="even">
<td align="left">rejeter <span class="math inline">\(\mathscr{H}_0\)</span></td>
<td align="center">erreur de type I</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
</tr>
</tbody>
</table>
<p>Pour prendre une décision, on doit comparer la valeur-<em>p</em> <span class="math inline">\(P\)</span> avec le niveau du test <span class="math inline">\(\alpha\)</span>:</p>
<ul>
<li>si <span class="math inline">\(P &lt; \alpha\)</span> on rejette <span class="math inline">\(\mathscr{H}_0\)</span>,</li>
<li>si <span class="math inline">\(P \geq \alpha\)</span> on ne rejette pas <span class="math inline">\(\mathscr{H}_0\)</span>.</li>
</ul>
<p>Attention à ne pas confondre niveau du test (probabilité fixée au préalable par l’expérimentateur) et la valeur-<em>p</em> (qui dépend de l’échantillon). Si vous faites un test à un niveau 5% la
probabilité de faire une erreur de type I est de 5% par définition, quelque soit la
valeur de la valeur-<em>p</em>. La valeur-<em>p</em> s’interprète comme la probabilité d’obtenir une valeur de
la statistique de test égale ou même plus grande que celle qu’on a observée dans l’échantillon, si <span class="math inline">\(\mathscr{H}_0\)</span> est vraie.</p>
</div>
<div id="puissance-statistique" class="section level3" number="1.1.5">
<h3><span class="header-section-number">1.1.5</span> Puissance statistique</h3>
<p>Le but du test d’hypothèse est de prouver (hors de tout doute raisonnable) qu’une différence ou un effet est significatif:: par exemple, si une nouvelle configuration d’un site web (hypothèse alternative) permet d’augmenter les ventes par rapport au statu quo. Notre capacité à détecter cette amélioration dépend de la puissance du test: plus cette dernière est élevée, plus grande est notre capacité à rejeter <span class="math inline">\(\mathscr{H}_0\)</span> quand ce dernier est faux.
Quand on ne rejette pas <span class="math inline">\(\mathscr{H}_0\)</span> et que <span class="math inline">\(\mathscr{H}_a\)</span> est en fait vraie, on commet une erreur de type II: cette dernière survient avec probabilité <span class="math inline">\(1-\gamma\)</span>. La <strong>puissance statistique</strong> d’un test est la probabilité que le test rejette <span class="math inline">\(\mathscr{H}_0\)</span> alors que <span class="math inline">\(\mathscr{H}_0\)</span> est fausse, soit
<span class="math display">\[\begin{align*}
\gamma = \mathsf{Pr}_a(\text{rejeter } \mathscr{H}_0)
\end{align*}\]</span>
Selon le choix de l’alternative, il est plus ou moins facile de rejeter l’hypothèse nulle en faveur de l’alternative.</p>
<div class="figure" style="text-align: center"><span id="fig:puissance1"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/puissance1-1.png" alt="Comparaison de la loi nulle (ligne pleine) et d'une alternative spécifique pour un test-$t$ (ligne traitillée). La puissance correspond à l'aire sous la courbe de la densité de la loi alternative qui est dans la zone de rejet du test (en blanc)." width="70%" />
<p class="caption">
Figure 1.1: Comparaison de la loi nulle (ligne pleine) et d’une alternative spécifique pour un test-<span class="math inline">\(t\)</span> (ligne traitillée). La puissance correspond à l’aire sous la courbe de la densité de la loi alternative qui est dans la zone de rejet du test (en blanc).
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:puissance2"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/puissance2-1.png" alt="Augmentation de la puissance suite à une augmentation de la différence de moyenne sous l'hypothèse alternative. La puissance est l'aire sous la courbe (blanc) de la loi alternative (ligne traitillée); cette dernière est plus décalée vers la droite par rapport à la loi nulle postulée (ligne pleine)." width="70%" />
<p class="caption">
Figure 1.2: Augmentation de la puissance suite à une augmentation de la différence de moyenne sous l’hypothèse alternative. La puissance est l’aire sous la courbe (blanc) de la loi alternative (ligne traitillée); cette dernière est plus décalée vers la droite par rapport à la loi nulle postulée (ligne pleine).
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:puissance3"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/puissance3-1.png" alt="Augmentation de la puissance suite à une augmentation de la taille de l'échantillon ou une diminution de l'écart-type de la population: la loi nulle (ligne pleine) est plus concentrée et la taille de la région de rejet diminue. La puissance est l'aire sous la courbe (blanc) de la loi alternative (ligne traitillée). Règle générale, la loi nulle change selon la taille de l'échantillon." width="70%" />
<p class="caption">
Figure 1.3: Augmentation de la puissance suite à une augmentation de la taille de l’échantillon ou une diminution de l’écart-type de la population: la loi nulle (ligne pleine) est plus concentrée et la taille de la région de rejet diminue. La puissance est l’aire sous la courbe (blanc) de la loi alternative (ligne traitillée). Règle générale, la loi nulle change selon la taille de l’échantillon.
</p>
</div>
<p>On veut qu’un test ait une puissance élevée, c’est-à-dire, on veut que <span class="math inline">\(\gamma\)</span> soit le plus près de 1 possible. Minimalement, la puissance du test devrait être <span class="math inline">\(\alpha\)</span> si on rejette l’hypothèse nulle une fraction <span class="math inline">\(\alpha\)</span> du temps quand cette dernière est vraie. La puissance dépend de plusieurs critères, à savoir:</p>
<ul>
<li>la taille de l’effet: plus la différence est grande entre la valeur du paramètre postulé <span class="math inline">\(\theta_0\)</span> sous <span class="math inline">\(\mathscr{H}_0\)</span> et le comportement observé, plus il est facile de le détecter (voir Figure <a href="intro.html#fig:puissance3">1.3</a>);</li>
<li>la variabilité: moins les observations sont variables, plus il est facile de déterminer que la différence observée est significative (les grandes différences sont alors moins plausibles, comme l’illustre la Figure <a href="intro.html#fig:puissance2">1.2</a>);</li>
<li>la taille de l’échantillon: plus on a d’observations, plus notre capacité à détecter une différence significative augmente parce que l’erreur-type décroît avec la taille de l’échantillon à un rythme (ordinairement) de <span class="math inline">\(n^{-1/2}\)</span>. La loi nulle devient aussi plus concentrée quand la taille de l’échantillon augmente.</li>
<li>le choix de la statistique de test: par exemple, les statistiques basées sur les rangs n’utilisent pas les valeurs numériques qu’à travers le rang relatif. Ces tests sont donc moins puissants parce qu’ils n’utilisent pas toute l’information dans l’échantillon; en contrepartie, ils sont souvent plus robustes en présence de valeurs aberrantes et si le modèle est mal spécifié. Les statistiques de test que nous choisirons sont souvent standards et parmi les plus puissantes qui soient, aussi on ne traitera pas de ce point davantage dans le cadre du cours.</li>
</ul>
<p>Pour calculer la puissance d’un test, il faut choisir une alternative spécifique. Pour des exemples simples de statistiques, on peut obtenir une formule pour la puissance: par exemple, si on utilise un test-<span class="math inline">\(t\)</span> pour un échantillon, la statistique <span class="math inline">\(T=\sqrt{n}(\overline{X}-\mu_0)/S_n \sim \mathcal{T}_{n-1}\)</span> et, si la vraie moyenne est <span class="math inline">\(\Delta + \mu_0\)</span>, alors la loi alternative est Student-<span class="math inline">\(t\)</span>, mais non-centrée avec paramètre de décalage <span class="math inline">\(\Delta\)</span>. Cette dérivation est l’exception plutôt que la règle et on détermine d’ordinaire la puissance à l’aide de méthodes de Monte Carlo en simulant des observations d’une alternative donnée, en calculant la statistique de test sur le nouvel échantillon simulé et en calculant la valeur-<em>p</em> associée à notre hypothèse nulle de façon répétée. On calcule par la suite la proportion de tests qui mènent au rejet de l’hypothèse nulle à niveau <span class="math inline">\(\alpha\)</span>, ce qui correspond au pourcentage de valeurs-<span class="math inline">\(p\)</span> inférieures à <span class="math inline">\(\alpha\)</span>.</p>
</div>
<div id="intervalle-de-confiance" class="section level3" number="1.1.6">
<h3><span class="header-section-number">1.1.6</span> Intervalle de confiance</h3>
<p>Un <strong>intervalle de confiance</strong> est une manière alternative de rapporter les conclusions d’un test, en ce sens qu’on fournit une estimation ponctuelle de <span class="math inline">\(\hat{\theta}\)</span> avec une marge d’erreur. L’intervalle de confiance donne donc une indication de la variabilité de la procédure d’estimation. Un intervalle de confiance de Wald à <span class="math inline">\((1-\alpha)\)</span> pour un paramètre <span class="math inline">\(\theta\)</span> est de la forme
<span class="math display">\[\begin{align*}
\widehat{\theta} \pm \mathfrak{q}_{\alpha/2} \; \mathrm{se}(\widehat{\theta})
\end{align*}\]</span>
où <span class="math inline">\(\mathfrak{q}_{\alpha/2}\)</span> est le quantile d’ordre <span class="math inline">\(1-\alpha/2\)</span> de la loi nulle de la statistique de Wald,
<span class="math display">\[\begin{align*}
T =\frac{\widehat{\theta}-\theta}{\mathrm{se}(\widehat{\theta})},
\end{align*}\]</span>
et où <span class="math inline">\(\theta\)</span> représente la valeur du paramètre <span class="math inline">\(\theta\)</span> (supposé fixe, mais inconnu) de la population. Les bornes de l’intervalle de confiance sont aléatoires puisque <span class="math inline">\(\widehat{\theta}\)</span> et <span class="math inline">\(\mathrm{se}(\widehat{\theta})\)</span> sont des variable aléatoires: leurs valeurs observées changent d’un échantillon à un autre.</p>
<p>Par exemple, pour un échantillon aléatoire <span class="math inline">\(X_1, \ldots, X_n\)</span> provenant d’une loi normale <span class="math inline">\(\mathsf{No}(\mu, \sigma)\)</span>, l’intervalle de confiance à <span class="math inline">\((1-\alpha)\)</span> pour la moyenne (dans la population) <span class="math inline">\(\mu\)</span> est
<span class="math display">\[\begin{align*}
\overline{X} \pm t_{n-1, \alpha/2} \frac{S}{\sqrt{n}}
\end{align*}\]</span>
où <span class="math inline">\(t_{n-1, \alpha/2}\)</span> est le quantile d’ordre <span class="math inline">\(1-\alpha/2\)</span> de la loi Student-<span class="math inline">\(t\)</span> avec <span class="math inline">\(n-1\)</span> degrés de libertés.</p>
<p>Avant qu’on calcule l’intervalle de confiance, il y a une probabilité de <span class="math inline">\(1-\alpha\)</span> que <span class="math inline">\(\theta\)</span> soit contenu dans l’intervalle <strong>aléatoire</strong> symmétrique <span class="math inline">\((\widehat{\theta} - \mathfrak{q}_{\alpha/2} \; \mathrm{se}(\widehat{\theta}), \widehat{\theta} + \mathfrak{q}_{\alpha/2} \; \mathrm{se}(\widehat{\theta}))\)</span>, où <span class="math inline">\(\widehat{\theta}\)</span> dénote l’estimateur de <span class="math inline">\(\theta\)</span>. Une fois qu’on obtient un échantillon et qu’on calcule les bornes de l’intervalle de confiance, il n’y a plus de notion de probabilité: la vraie valeur du paramètre <span class="math inline">\(\theta\)</span> (inconnue) est soit contenue dans l’intervalle de confiance, soit pas. La seule interprétation de l’intervalle de confiance qui soit valable alors est la suivante: si on répète l’expérience plusieurs fois et qu’à chaque fois on calcule un intervalle de confiance à <span class="math inline">\(1-\alpha\)</span>, alors une proportion de <span class="math inline">\((1-\alpha)\)</span> de ces intervalles devraient contenir la vraie valeur de <span class="math inline">\(\theta\)</span> (de la même manière, si vous lancez une pièce de monnaie équilibrée, vous devriez obtenir grosso modo une fréquence de 50% de pile et 50% de face, mais chaque lancer donnera un ou l’autre de ces choix). Notre « confiance » est dans la procédure et non pas dans les valeurs numériques obtenues pour un échantillon donné.</p>
<div class="figure" style="text-align: center"><span id="fig:intconf"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/intconf-1.png" alt="Intervalles de confiance à 95\% pour la moyenne d'une population normale $\mathsf{No}(0,1)$ pour 100 échantillons aléatoires. En moyenne, 5\% de ces intervalles (en rouge) n'incluent pas la vraie valeur de la moyenne de zéro." width="70%" />
<p class="caption">
Figure 1.4: Intervalles de confiance à 95% pour la moyenne d’une population normale <span class="math inline">\(\mathsf{No}(0,1)\)</span> pour 100 échantillons aléatoires. En moyenne, 5% de ces intervalles (en rouge) n’incluent pas la vraie valeur de la moyenne de zéro.
</p>
</div>
<p>Si on s’intéresse seulement à la décision rejeter/ne pas rejeter <span class="math inline">\(\mathscr{H}_0\)</span>, l’intervalle de confiance est équivalent à la valeur-<em>p</em> en ce sens qu’il mène à la même décision. L’intervalle de confiance donne en revanche l’ensemble des valeurs pour lesquelles la statistique de test ne fournit pas assez de preuves pour rejeter <span class="math inline">\(\mathscr{H}_0\)</span>: pour un test à niveau <span class="math inline">\(\alpha\)</span>, on ne rejetterait aucune des valeurs contenues dans l’intervalle de confiance de niveau <span class="math inline">\(1-\alpha\)</span>. Si la valeur-<em>p</em> est inférieure à <span class="math inline">\(\alpha\)</span>, la valeur postulée pour <span class="math inline">\(\theta\)</span> est donc hors de l’intervalle de confiance calculé. À l’inverse, la valeur-<em>p</em> ne donne la probabilité d’obtenir un résultat aussi extrême sous l’hypothèse nulle que pour une seule valeur numérique, mais permet de quantifier précisément à quel point le résultat est extrême.</p>

<div class="example">
<span id="exm:achats-milleniaux" class="example"><strong>Exemple 1.1  (Achat en ligne de milléniaux)  </strong></span>
Supposons qu’une chercheuse veut faire une étude sur l’évolution des ventes en ligne au Canada. Elle postule que les membres de la génération Y fait plus d’achats en ligne que ceux des générations antérieures. Pour répondre à cette question, un sondage est envoyé à un échantillon aléatoire de <span class="math inline">\(n=500\)</span> individus représentatif de la population avec 160 membres de la génération Y et 340 personnes plus âgées. La variable réponse est le montant d’achat effectués en ligne dans le mois dernier (en dollars).
</div>
<p>Dans cet exemple, on s’intéresse à la différence entre le montant moyen des Y et celui des générations antérieures: la différence de moyenne observée dans l’échantillon est de 16.49 dollars et donc les milléniaux ont dépensé davantage. En revanche, notre échantillon est aléatoire et le montant d’achat en ligne varie d’un individu à l’autre (et d’un mois à l’autre): ce n’est donc pas suffisant pour dire que la différence est significative.</p>
<p>La première étape de notre analyse consiste à définir les quantités d’intérêt et à formuler nos hypothèse en fonction de paramètres du modèle; il convient également de définir ces derniers en fonction des variables en présence dans l’exemple. Ici, on considère un test pour la différence de moyenne dans les populations postulées <span class="math inline">\(\mu_1\)</span> (pour la génération Y) et <span class="math inline">\(\mu_2\)</span> (pour les générations antérieures) d’écart-type respectif <span class="math inline">\(\sigma_1\)</span> et <span class="math inline">\(\sigma_2\)</span>. Comment déterminer quelle hypothèse on considère? Comme statisticien, on se fait l’avocat du Diable: l’hypothèse d’intérêt du chercheur est l’hypothèse alternative et ici, <span class="math inline">\(\mathscr{H}_a: \mu_1 &gt; \mu_2\)</span>, où <span class="math inline">\(\mu_1\)</span> représente la moyenne des achats mensuels des milléniaux. L’hypothèse nulle comprend toutes les autres valeurs pour la différence de moyenne, soit <span class="math inline">\(\mathscr{H}_0: \mu_1 \leq \mu_2\)</span>. Il suffit néanmoins de considérer le cas <span class="math inline">\(\mu_1=\mu_2\)</span> (pourquoi?)</p>
<p>La deuxième étape consiste à choisir une statistique de test. S’il n’y a aucune différence de moyenne entre les groupes, alors <span class="math inline">\(\overline{X}_1-\overline{X}_2\)</span> a moyenne zéro et la différence de moyenne a une variance de <span class="math inline">\(\sigma^2_1/n_1+\sigma^2_2/n_2\)</span>. Ici, on considère la statistique de <span class="citation"><a href="references.html#ref-Welch1947" role="doc-biblioref">Welch</a> (<a href="references.html#ref-Welch1947" role="doc-biblioref">1947</a>)</span> pour une différence de moyenne entre deux échantillons:
<span class="math display">\[\begin{align*}
T = \frac{\overline{X}_1 - \overline{X}_2}{\left(\frac{S_1^2}{n_1}+\frac{S_2^2}{n_2} \right)^{1/2}}, \end{align*}\]</span>
où <span class="math inline">\(\overline{X}_i\)</span> est la moyenne empirique dans l’échantillon <span class="math inline">\(i\)</span> (<span class="math inline">\(i=1, 2\)</span>) et <span class="math inline">\(S_i^2\)</span> est la variance empirique et <span class="math inline">\(n_i\)</span> la taille de l’échantillon du groupe <span class="math inline">\(i\)</span>. La statistique est utilisée pour calculer la différence de moyennes de deux échantillons de variance potentiellement différente. La valeur de la statistique dans l’échantillon est <span class="math inline">\(T=2.76\)</span>, mais on obtiendrait une valeur différente avec un autre échantillon. Il convient donc de déterminer si cette valeur est compatible avec notre hypothèse nulle en la comparant à la loi nulle sous <span class="math inline">\(\mathscr{H}_0\)</span> de <span class="math inline">\(T\)</span>. On effectuera le test à niveau <span class="math inline">\(\alpha=0.05\)</span>.</p>
<p>La troisième étape est l’obtention d’un étalon de mesure pour déterminer si notre résultat est extrême ou inattendu. Vous remarquerez que la statistique de Welch a moyenne zéro et variance un sous l’hypothèse nulle que <span class="math inline">\(\mu_1=\mu_2\)</span>: standardiser une statistique permet d’obtenir un objet dont on connaît le comportement pour de grands échantillons et obtenir une quantité sans unité de mesure. La dérivation de la loi nulle est hors objectifs du cours, aussi cette dernière vous sera donnée dans tous les cas qu’on considère. Asymptotiquement, <span class="math inline">\(T\)</span> suit une loi normale <span class="math inline">\(\mathsf{No}(0, 1)\)</span>, mais il existe une meilleure approximation pour <span class="math inline">\(n\)</span> petit; on compare le comportement de <span class="math inline">\(T\)</span> à l’aide d’une loi de Student (à l’aide de l’approximation de <span class="citation"><a href="references.html#ref-Satterthwaite1946" role="doc-biblioref">Satterthwaite</a> (<a href="references.html#ref-Satterthwaite1946" role="doc-biblioref">1946</a>)</span>).</p>
<p>La dernière étape consiste à obtenir une valeur-<em>p</em>, soit la probabilité d’observer un résultat aussi extrême sous <span class="math inline">\(\mathscr{H}_0\)</span>: l’avantage de la valeur-<em>p</em> est que cette valeur est une probabilité (dans <span class="math inline">\([0, 1]\)</span>) et qu’elle suit une loi uniforme sous <span class="math inline">\(\mathscr{H}_0\)</span>. Puisque nous avons une hypothèse alternative unilatérale, on regarde la probabilité sous <span class="math inline">\(\mathscr{H}_0\)</span> que <span class="math inline">\(\mathsf{Pr}(T &gt; t)\)</span>. La valeur-<em>p</em> vaut <span class="math inline">\(0.0031\)</span> et donc, à niveau 5%, on rejette l’hypothèse nulle pour conclure que la génération Y dépense davantage en ligne que les générations antérieures.</p>

<div class="example">
<span id="exm:prix-trains-tests" class="example"><strong>Exemple 1.2  (Prix de billets de trains à grande vitesse espagnols)  </strong></span>La compagnie nationale de chemin de fer <a href="https://www.renfe.com/">Renfe</a> gère les trains régionaux et les trains à haute vitesse dans toute l’Espagne. Les prix des billets vendus par Renfe sont <a href="https://www.kaggle.com/thegurusteam/spanish-high-speed-rail-system-ticket-pricing">aggrégés</a> par une compagnie. On s’intéresse ici à une seule ligne, Madrid–Barcelone. Notre question scientifique est la suivante: est-ce que le prix des billets pour un aller (une direction) est plus chère pour un retour? Pour ce faire, on considère un échantillon de 10000 billets entre les deux plus grandes villes espagnoles. On s’intéresse au billets de TGV vendus (AVE) au tarif Promotionnel. Notre statistique de test sera simplement la différence de moyenne entre les deux échantillons: la différence entre le prix en euros d’un train Madrid–Barcelone (<span class="math inline">\(\mu_1\)</span>) et le prix d’un billet Barcelone–Madrid (<span class="math inline">\(\mu_2\)</span>) est <span class="math inline">\(\mu_1-\mu_2\)</span> et notre hypothèse nulle est qu’il n’y a aucune différence de prix, soit <span class="math inline">\(\mathscr{H}_0: \mu_1-\mu_2=0\)</span>. On utilise de nouveau le test de Welch pour deux échantillons.
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manipulation de données, incluant %&gt;%</span></span>
<span id="cb1-2"><a href="intro.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poorman)</span>
<span id="cb1-3"><a href="intro.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données</span></span>
<span id="cb1-4"><a href="intro.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(renfe, <span class="at">package =</span> <span class="st">&quot;hecmodstat&quot;</span>)</span>
<span id="cb1-5"><a href="intro.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(renfe, <span class="at">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 7
##    prix type    classe     tarif    dest             duree jour 
##   &lt;dbl&gt; &lt;fct&gt;   &lt;fct&gt;      &lt;fct&gt;    &lt;fct&gt;            &lt;dbl&gt; &lt;fct&gt;
## 1 143.  AVE     Preferente Promo    Barcelone-Madrid   190 6    
## 2 182.  AVE     Preferente Flexible Barcelone-Madrid   190 2    
## 3  86.8 AVE     Preferente Promo    Barcelone-Madrid   165 7    
## 4  86.8 AVE     Preferente Promo    Barcelone-Madrid   190 7    
## 5  69.0 AVE-TGV Preferente Promo    Barcelone-Madrid   175 4</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sous-échantillon avec uniquement les données au tarif promotionnel</span></span>
<span id="cb3-2"><a href="intro.html#cb3-2" aria-hidden="true" tabindex="-1"></a>renfe_promo <span class="ot">&lt;-</span> renfe <span class="sc">%&gt;%</span> <span class="fu">subset</span>(tarif <span class="sc">==</span> <span class="st">&quot;Promo&quot;</span>)</span>
<span id="cb3-3"><a href="intro.html#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Test-t et différence de moyenne</span></span>
<span id="cb3-4"><a href="intro.html#cb3-4" aria-hidden="true" tabindex="-1"></a>ttest <span class="ot">&lt;-</span> <span class="fu">t.test</span>(prix<span class="sc">~</span>dest, <span class="at">data =</span> renfe_promo)</span>
<span id="cb3-5"><a href="intro.html#cb3-5" aria-hidden="true" tabindex="-1"></a>ttest <span class="co">#imprimer le résultat</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  prix by dest
## t = -1, df = 8040, p-value = 0.2
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.100  0.209
## sample estimates:
## mean in group Barcelone-Madrid mean in group Madrid-Barcelone 
##                           82.1                           82.6</code></pre>
<p>Plutôt que d’utiliser la loi asymptotique (qui est valide pour de grands échantillons à cause du théorème central limite), on peut considérer une approximation sous une hypothèse moins restrictive en supposant que les données sont échangeables. Sous l’hypothèse nulle, il n’y aucune différence entre les deux destinations et les étiquettes pour la destination (une variable catégorielle binaire) sont arbitraires. On pourrait considérer les mêmes données, mais avec une permutation des variables explicatives: c’est ce qu’on appelle un <a href="https://www.jwilber.me/permutationtest/">test de permutation</a>. On va recréer deux groupes de taille identique à notre échantillon original, mais en changeant les observations. On recalcule la statistique de test sur ces nouvelle données (si on a une poignée d’observations, il est possible de lister toutes les permutations possibles; typiquement, il suffit de considérer un grand nombre de telles permutations, disons 9999). Pour chaque nouveau jeu de données, on calculera la statistique de test et on calculera le rang de notre statistique par rapport à cette référence. Si la valeur de notre statistique observée sur l’échantillon original est extrême en comparaison, c’est autant de preuves contre l’hypothèse nulle.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="intro.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valeur-p par permutation</span></span>
<span id="cb5-2"><a href="intro.html#cb5-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(renfe_promo)</span>
<span id="cb5-3"><a href="intro.html#cb5-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fl">1e4</span></span>
<span id="cb5-4"><a href="intro.html#cb5-4" aria-hidden="true" tabindex="-1"></a>ttest_stats <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B) </span>
<span id="cb5-5"><a href="intro.html#cb5-5" aria-hidden="true" tabindex="-1"></a>ttest_stats[<span class="dv">1</span>] <span class="ot">&lt;-</span> ttest<span class="sc">$</span>statistic</span>
<span id="cb5-6"><a href="intro.html#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20200608</span>) <span class="co"># germe pour nombres pseudo-aléatoires</span></span>
<span id="cb5-7"><a href="intro.html#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>B){</span>
<span id="cb5-8"><a href="intro.html#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Recalculer la statistique de test, mais permuter les étiquettes</span></span>
<span id="cb5-9"><a href="intro.html#cb5-9" aria-hidden="true" tabindex="-1"></a>  ttest_stats[i] <span class="ot">&lt;-</span> <span class="fu">t.test</span>(prix <span class="sc">~</span> dest[<span class="fu">sample.int</span>(<span class="at">n =</span> n)], </span>
<span id="cb5-10"><a href="intro.html#cb5-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> renfe_promo)<span class="sc">$</span>statistic</span>
<span id="cb5-11"><a href="intro.html#cb5-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-12"><a href="intro.html#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Bibliothèque graphique</span></span>
<span id="cb5-13"><a href="intro.html#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-14"><a href="intro.html#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracer un graphique de la distribution empirique obtenue par permutation</span></span>
<span id="cb5-15"><a href="intro.html#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">statistique =</span> ttest_stats), </span>
<span id="cb5-16"><a href="intro.html#cb5-16" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>statistique)) <span class="sc">+</span></span>
<span id="cb5-17"><a href="intro.html#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span> </span>
<span id="cb5-18"><a href="intro.html#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span> </span>
<span id="cb5-19"><a href="intro.html#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ttest_stats[<span class="dv">1</span>]) <span class="sc">+</span> </span>
<span id="cb5-20"><a href="intro.html#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;densité&quot;</span>) <span class="sc">+</span> </span>
<span id="cb5-21"><a href="intro.html#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:renfepermut"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/renfepermut-1.png" alt="Approximation par permutation de la loi nulle de la statistique de test de Welch (histogramme et trait noir) et loi asymptotique normale standard (trait bleu) pour le prix de billets de trains AVE au tarif promotionnel entre Madrid et Barcelone. La valeur de la statistique de test de l'échantillon original est représentée par un trait vertical." width="70%" />
<p class="caption">
Figure 1.5: Approximation par permutation de la loi nulle de la statistique de test de Welch (histogramme et trait noir) et loi asymptotique normale standard (trait bleu) pour le prix de billets de trains AVE au tarif promotionnel entre Madrid et Barcelone. La valeur de la statistique de test de l’échantillon original est représentée par un trait vertical.
</p>
</div>
<p>La valeur-<em>p</em> du test de permutation, <span class="math inline">\(0.186\)</span>, est la proportion de statistiques plus extrêmes que celle observée. Cette valeur-<em>p</em> est quasi-identique à celle de l’approximation de Satterthwaite, à savoir <span class="math inline">\(0.182\)</span> (la loi Student-<span class="math inline">\(t\)</span> est numériquement équivalente à une loi standard normale avec autant de degrés de liberté), tel que représenté dans la Figure <a href="intro.html#fig:renfepermut">1.5</a>. Malgré que notre échantillon soit très grand, avec <span class="math inline">\(n=8059\)</span> observations, la différence n’est pas jugée significative. Avec un échantillon de deux millions de billets, on pourrait estimer précisément la moyenne (au centime près): la différence de prix entre les deux destinations et cette dernière deviendrait statistiquement significative. Elle n’est pas en revanche pertinente (une différence de <span class="math inline">\(0.28\)</span> euros sur un prix moyen de <span class="math inline">\(82.56\)</span> euros est quantité négligeable).</p>
</div>
</div>
<div id="analyse-exploratoire" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Analyse exploratoire de données</h2>
<p>L’analyse exploratoire, comme son nom l’indique, est une étape préliminaire à la modélisation servant à l’acquisition d’une meilleure compréhension des données.
Une connaissance rudimentaire des graphiques est nécessaire et on s’attardera aux <a href="https://rstudio.cloud/learn/primers/1.1">rudiments de la visualisation graphique</a>. Plusieurs ouvrages abordent ces notions (en anglais) .</p>
<ul>
<li><a href="https://r4ds.had.co.nz/exploratory-data-analysis.html">Chapitre 3 de <em><strong>R</strong> for Data Science</em> par Garrett Grolemund et Hadley Wickham</a></li>
<li><a href="https://www.openintro.org/book/isrs/">Section 1.6 du livre <em>Introductory Statistics with Randomization and Simulation</em> d’OpenIntro</a></li>
<li><a href="https://clauswilke.com/dataviz/"><em>Fundamentals of Data Visualization</em> par Claus O. Wilke</a></li>
<li><a href="https://socviz.co/lookatdata.html#lookatdata">Chapitre 1 de <em>Data Visualization: A practical introduction</em> par Kieran Healy</a></li>
</ul>
<p>Si l’analyse exploratoire est souvent négligée dans les cours de statistique (parce qu’elle n’a pas de fondement mathématique), elle n’en est pas moins importante car elle nous sert à interpréter les données dans le contexte du problème et à nous assurer que notre analyse ou notre traitement de ces dernières est cohérent. Le sujet est difficile à cerner, puisque c’est davantage un art qu’une approche rigoureuse; Grolemund et Wickham parlent même « d’état d’esprit ». Le but de l’analyse exploratoire graphique est d’extraire des informations utiles, le plus souvent par le biais d’une série de questions qui sont raffinées au fur et à mesure que progresse l’analyse. On s’intéresse particulièrement aux relations et interactions entre différentes variables et la distribution empirique de chaque variable. Les étapes majeures sont:</p>
<ol style="list-style-type: decimal">
<li>Formuler des questions sur les données</li>
<li>Chercher des réponses à ces questions à l’aide de statistiques descriptives, de tableaux de fréquence ou de contingence et de graphiques.</li>
<li>Raffiner nos questions, et utiliser les trouvailles pour peaufiner notre analyse</li>
</ol>
<p>Dans un rapport, un résumé des caractéristiques les plus importantes devrait être inclut pour que le lecteur ou la lectrice puisse valider son interprétation des données.</p>
<div id="soignez-votre-travail" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Soignez votre travail</h3>
<p>Si vous incluez un graphique (ou un tableau), il est important d’ajouter une légende qui décrit le graphique et le résume, les noms de variables (avec les unités) sur les axes, mais aussi de soigner le rendu et le formatage pour obtenir un produit fini propre, lisible et cohérent: en particulier, votre description devrait coïncider avec le rendu. Votre graphique raconte une histoire, aussi prenez-soin que cette dernière soit nécessaire et attrayante.</p>
</div>
<div id="types-de-variables" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Types de variables</h3>
<p>Commençons par parler des données: celles que l’on manipulera dans ce cours sont stockées sous forme tabulaire. Dans une base de donnée en format long, chaque ligne correspond à une observation et chaque colonne à une variable; les entrées de la base de données contiennent les valeurs.</p>
<p>L’alternative au format long est le format court/large, où les colonnes représentent les modalités de variables catégorielles et il peut y avoir plusieurs valeurs par ligne qui contiennent des valeurs de la variable réponse. Le schéma de la Figure <a href="intro.html#fig:longvswide">1.6</a> permet de mieux comprendre la distinction entre les deux formats: on supposera que nos données sont toujours en format long, ce dernier étant assumé par défaut par le logiciel pour procéder à l’ajustement d’un modèle..</p>
<div class="figure" style="text-align: center"><span id="fig:longvswide"></span>
<img src="images/original-dfs-tidy.png" alt="Format long versus format large (_wide_) (dessin de Garrick Aden-Buie)." width="70%" />
<p class="caption">
Figure 1.6: Format long versus format large (<em>wide</em>) (dessin de Garrick Aden-Buie).
</p>
</div>
<ul>
<li>Une <strong>variable</strong> représente une caractéristique de la population d’intérêt, par exemple le sexe d’un individu, le prix d’un article, etc.</li>
<li>une <strong>observation</strong>, parfois appelée donnée, est un ensemble de mesures collectées sous des conditions identiques, par exemple pour un individu ou à un instant donné.</li>
</ul>
<p>Le choix de modèle statistique ou de test dépend souvent du type de variables collectées. Les variables peuvent être de plusieurs types: quantitatives (discrètes ou continues) si elles prennent des valeurs numériques, qualitatives (binaires, nominales ou ordinales) si elles sont décrites par un adjectif; je préfère le terme catégorielle, plus évocateur.</p>
<!-- ```{r variablesquanti, fig.cap = "Illustration par Allison Horst de variables continues (gauche) et discrètes (droite).", echo = FALSE} -->
<!-- knitr::include_graphics('images/continuous_discrete.png') -->
<!-- ``` -->
<p>Les modèles de régression servent à expliquer des variables quantitatives en fonction d’autres caractéristiques.</p>
<ul>
<li>une variable discrète prend un nombre dénombrable de valeurs; ce sont souvent des variables de dénombrement ou des variables dichotomiques.</li>
<li>une variable continue peut prendre (en théorie) une infinité de valeurs, même si les valeurs mesurées sont arrondies ou mesurées avec une précision limitée (temps, taille, masse, vitesse, salaire). Dans bien des cas, nous pouvons considérer comme continues des variables discrètes si elles prennent un assez grand nombre de valeurs.</li>
</ul>
<p>Les variables catégorielles représentent un ensemble fini de possibilités. On les regroupe en deux types, pour lesquels on ne fera pas de distinction: nominales s’il n’y a pas d’ordre entre les modalités (sexe, couleur, pays d’origine) ou ordinale (échelle de Likert, tranche salariale). La codification des modalités des variables catégorielle est arbitraire; en revanche, on préservera l’ordre lorsqu’on représentera graphiquement les variables ordinales. Lors de l’estimation, chaque variable catégorielle doit est transformée en un ensemble d’indicateurs binaires: il est donc essentiel de déclarer ces dernières dans votre logiciel statistique, surtout si elles sont parfois encodées dans la base de données à l’aide de valeurs entières.</p>
<!-- ```{r variablescateg, fig.cap = "Illustration par Allison Horst de variables catégorielles nominales (gauche), ordinales (centre) et binaires (droite).", echo = FALSE} -->
<!-- knitr::include_graphics('images/nominal_ordinal_binary.png') -->
<!-- ``` -->
</div>
<div id="graphiques" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Graphiques</h3>
<p>Le principal type de graphique pour représenter la distribution d’une variable catégorielle est le diagramme en bâtons, dans lequel la fréquence de chaque catégorie est présentée sur l’axe des ordonnées (<span class="math inline">\(y\)</span>) en fonction de la modalité, sur l’axe des abscisses (<span class="math inline">\(x\)</span>), et ordonnées pour des variables ordinales. Cette représentation est en tout point supérieur au <a href="http://www.perceptualedge.com/articles/08-21-07.pdf">diagramme en camembert</a>, une engeance répandu qui devrait être honnie (notamment parce que l’humain juge mal les différences d’aires, qu’une simple rotation change la perception du graphique et qu’il est difficile de mesurer les proportions) — ce n’est pas de la tarte!</p>
<div class="figure" style="text-align: center"><span id="fig:barplotrenfe"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/barplotrenfe-1.png" alt="Diagramme en bâtons pour la classe des billets de trains du jeu de données Renfe." width="70%" />
<p class="caption">
Figure 1.7: Diagramme en bâtons pour la classe des billets de trains du jeu de données Renfe.
</p>
</div>
<p>Puisque les variables continues peuvent prendre autant de valeurs distinctes qu’il y a d’observations, on ne peut simplement compter le nombre d’occurrence par valeur unique. On regroupera plutôt dans un certain nombre d’intervalle, en discrétisant l’ensemble des valeurs en classes pour obtenir un histogramme. Le nombre de classes dépendra du nombre d’observations si on veut que l’estimation ne soit pas impactée par le faible nombre d’observations par classe: règle générale, le nombre de classes ne devrait pas dépasser <span class="math inline">\(\sqrt{n}\)</span>, où <span class="math inline">\(n\)</span> est le nombre d’observations de l’échantillon. On obtiendra la fréquence de chaque classe, mais si on normalise l’histogramme (de façon à ce que l’aire sous les bandes verticales égale un), on obtient une approximation discrète de la fonction de densité. Faire varier le nombre de classes permet parfois de faire apparaître des caractéristiques de la variable (notamment la multimodalité, l’asymmétrie et les arrondis).</p>
<p>Puisque qu’on groupe les observations en classe pour tracer l’histogramme, il est difficile de voir l’étendue des valeurs que prenne la variable: on peut rajouter des traits sous l’histogramme pour représenter les valeurs uniques prises par la variable, tandis que la hauteur de l’histogramme nous renseigne sur leur fréquence relative.</p>
<div class="figure" style="text-align: center"><span id="fig:histrenfe"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/histrenfe-1.png" alt="Histogramme du prix des billets au tarif Promo de trains du jeu de données Renfe" width="70%" />
<p class="caption">
Figure 1.8: Histogramme du prix des billets au tarif Promo de trains du jeu de données Renfe
</p>
</div>
<p>Une boîte à moustaches(<em>boxplot</em>) représente graphiquement cinq statistiques descriptives.</p>
<ul>
<li>La boîte donne les 1e, 2e et 3e quartiles <span class="math inline">\(q_1, q_2, q_3\)</span>. Il y a donc 50% des observations sont au-dessus/en-dessous de la médiane <span class="math inline">\(q_2\)</span> qui sépare en deux la boîte.</li>
<li>La longueur des moustaches est moins de <span class="math inline">\(1.5\)</span> fois l’écart interquartile <span class="math inline">\(q_3-q_1\)</span> (tracée entre 3e quartile et le dernier point plus petit que <span class="math inline">\(q_3+1.5(q_3-q_1)\)</span>, etc.)</li>
<li>Les observations au-delà des moustaches sont encerclées. Notez que plus le nombre d’observations est élevé, plus le nombres de valeurs aberrantes augmente. C’est un défaut de la boîte à moustache, qui a été conçue pour des jeux de données qui passeraient pour petits selon les standards actuels.</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:boiteamoustache"></span>
<img src="images/01-intro-boiteamoustache.png" alt="Boîte à moustache." width="70%" />
<p class="caption">
Figure 1.9: Boîte à moustache.
</p>
</div>
<p>On peut représenter la distribution d’une variable réponse continue en fonction d’une variable catégorielle en traçant une boîte à moustaches pour chaque catégorie et en les disposant côte-à-côte. Une troisième variable catégorielle peut être ajoutée par le biais de couleurs, comme dans la Figure <a href="intro.html#fig:histboxplot">1.10</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:histboxplot"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/histboxplot-1.png" alt="Boîte à moustaches du prix des billets au tarif Promo en fonction de la classe pour le jeu de données Renfe." width="70%" />
<p class="caption">
Figure 1.10: Boîte à moustaches du prix des billets au tarif Promo en fonction de la classe pour le jeu de données Renfe.
</p>
</div>
<p>Si on veut représenter la covariabilité de deux variables continues, on utilise un nuage de points où chaque variable est représentée sur un axe et chaque observation donne la coordonnée des points. Si la représentation graphique est dominée par quelques valeurs très grandes, une transformation des données peut être utile: vous verrez souvent des données positives à l’échelle logarithmique. Avec des données massives, les points seront superposés et le diagramme risque d’être illisible. Parmi les solutions envisagées, l’utilisation de la transparence, qui permet de voir où les points sont plus fréquents, ou encore un diagramme avec des classes hexagonale, l’équivalent d’un histogramme bidimensionnel où on remplace les classes par des hexagones. Le panneau de gauche de la Figure <a href="intro.html#fig:nuagedepoints">1.11</a> représente ainsi 100 observations simulées à l’aide d’un nuage de points 100 observations, tandis simulées. Dans le panneau de droite, on utilise plutôt un diagramme hexagonal pour représenter les 10 000 points, ce qui donne un aperçu de la densité conjointe des deux variables.</p>
<div class="figure" style="text-align: center"><span id="fig:nuagedepoints"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/nuagedepoints-1.png" alt="Nuage de points (gauche) et diagramme hexagonal (droite) pour des données simulées." width="70%" />
<p class="caption">
Figure 1.11: Nuage de points (gauche) et diagramme hexagonal (droite) pour des données simulées.
</p>
</div>
<p>Certaines données ont une structure particulière: pensons aux séries chronologiques, aussi appelées séries temporelles, qui comportent des observations ordonnées dans le temps. On représente chaque variable d’une série chronologique (sur l’axe des <span class="math inline">\(y\)</span>) en fonction du temps (sur l’axe des <span class="math inline">\(x\)</span>). Il est d’usage de relier les observations, bien que cet aperçu soit parfois trompeur.</p>
<div class="figure" style="text-align: center"><span id="fig:seriechrono"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/seriechrono-1.png" alt="Représentation graphique d'une série chronologique." width="70%" />
<p class="caption">
Figure 1.12: Représentation graphique d’une série chronologique.
</p>
</div>
<p>Plutôt que de décrire plus en détail le processus de l’analyse exploratoire, on présente un exemple qui illustre le cheminement habitue sur les données de trains de la Renfe introduites précédemment.</p>

<div class="example">
<span id="exm:renfe-aed" class="example"><strong>Exemple 1.3  (Analyse exploratoire des trains Renfe)  </strong></span>La première étape consisterait à lire la description de la base de données. Le jeu de données <code>renfe</code> contient les variables suivantes
</div>
<ul>
<li><code>prix</code>: prix du billet (en euros);</li>
<li><code>dest</code>: indicateur binaire du trajet, soit de Barcelone vers Madrid (<code>0</code>) ou de Madrid vers Barcelone (<code>1</code>);</li>
<li><code>tarif</code>: variable catégorielle indiquant le tarif du billet, un parmi <code>AdultoIda</code>, <code>Promo</code> et <code>Flexible</code>;</li>
<li><code>classe</code>: classe du billet, soit <code>Preferente</code>, <code>Turista</code>, <code>TuristaPlus</code> ou <code>TuristaSolo</code>;</li>
<li><code>type</code>: variable catégorielle indiquant le type de train, soit Alta Velocidad Española (<code>AVE</code>), soit Alta Velocidad Española conjointement avec TGV (un partenariat entre la SNCF et Renfe pour les trains à destination ou en provenance de Toulouse) <code>AVE-TGV</code>, soit les trains régionaux <code>REXPRESS</code>; seuls les trains étiquetés <code>AVE</code> ou <code>AVE-TGV</code> sont des trains à grande vitesse.</li>
<li><code>duree</code>: longueur annoncée du trajet (en minutes);</li>
<li><code>jour</code> entier indiquant le jour de la semaine du départ allant de dimanche (<code>1</code>) à samedi (<code>7</code>).</li>
</ul>
<p>Il n’y a pas de valeurs manquantes et un aperçu des données (<code>head(renfe)</code>) montre qu’elles sont en format long, ce qui veut dire que chaque ligne contient une seule valeur pour la variable réponse, ici le prix d’un billet de train. On entame l’analyse exploratoire avec des questions plutôt vagues, par exemple</p>
<ol style="list-style-type: decimal">
<li>Quels sont les facteurs déterminant le prix et le temps de parcours?</li>
<li>Est-ce que le temps de parcours est le même peut importe le type de train?</li>
<li>Quelles sont les caractéristiques distinctives des types de train?</li>
<li>Quelles sont les principales différences entre les tarifs?</li>
</ol>
<p>À l’exception de <code>prix</code> et de <code>duree</code>, toutes les variables explicatives sont catégorielles et stockées sous forme de facteur (<code>factor</code>). S’il faut déclarer chacune de ces variables, on porte une attention particulière à <code>jour</code> pour éviter les mauvaises surprises ultérieures.</p>
<p>On peut utiliser <code>str</code> pour obtenir un aperçu des données; la fonction <code>summary</code> permet d’obtenir des statistiques descriptives selon que les variables sont continues (minimum, maximum, moyenne, quartiles) ou catégoriells (fréquence); la fonction rapport aussi le nombre de valeurs manquantes (<code>NA</code>) par variable.</p>
<p>La manipulation de variables dans des bases de données est parfois loin d’être toujours élégante en <strong>R</strong>: on accès aux variables avec <code>$</code>, par exemple <code>renfe$prix</code>. Une alternative plus lisible et modulaire est d’utiliser l’opérateur tuyau (<code>%&gt;%</code>), qui permet de créer une chaîne logique de commandes; la fonction <code>count</code> sert à compter le nombre d’instance de chaque modalité (ces fonctionnalités ne sont pas disponibles dans <strong>R</strong> par défaut, mais avec les paquetages <code>tidyverse</code> ou l’alternative minimale <code>poorman</code>, préalablement chargée).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="intro.html#cb6-1" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> <span class="fu">count</span>(classe)</span></code></pre></div>
<pre><code>##        classe    n
## 1  Preferente  809
## 2     Turista 7197
## 3 TuristaPlus 1916
## 4 TuristaSolo   78</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="intro.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># un raccourci pour la même syntaxe</span></span>
<span id="cb8-2"><a href="intro.html#cb8-2" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span> <span class="fu">tally</span>()</span></code></pre></div>
<pre><code>##       type    n
## 1      AVE 9174
## 2  AVE-TGV  429
## 3 REXPRESS  397</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="intro.html#cb10-1" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(tarif) <span class="sc">%&gt;%</span> <span class="fu">tally</span>()</span></code></pre></div>
<pre><code>##       tarif    n
## 1 AdultoIda  397
## 2  Flexible 1544
## 3     Promo 8059</code></pre>
<p>En analysant le nombre de trains dans les catégories, on remarque qu’il y a autant de billets de type <code>REXPRESS</code> que le nombre de billets au tarif <code>AdultoIda</code>. On peut faire le décompte par catégorie avec un tableau de contingence, qui compte le nombre respectif dans chaque sous-catégorie. Dans la base de données Renfe, tous les billets pour les RegioExpress sont vendus au tarif <code>AdultoIda</code> en classe <code>Turista</code>. Le nombre de billets est minime, à peine 397 sur 10000. Cela suggère une nouvelle question: pourquoi ces trains sont-ils si peu populaires?</p>
<pre><code>##       tarif     type    n
## 1 AdultoIda REXPRESS  397
## 2  Flexible      AVE 1446
## 3  Flexible  AVE-TGV   98
## 4     Promo      AVE 7728
## 5     Promo  AVE-TGV  331</code></pre>
<p>On remarque également que seulement 17 temps de parcours sont affichés sur les billets (<code>renfe %&gt;% distinct(duree)</code> ou <code>unique(renfe$duree)</code>). On peut donc penser que la durée affichée sur le billet (en minutes) est le temps de trajet annoncé. La majeure partie (15 sur 17) des temps de parcours sont sous la barre des 3h15, hormis deux qui dépassent les 9h! Selon Google Maps, les deux villes sont distantes de 615km par la route, 500km à vol d’oiseau. Cela implique que, vraisemblablement, certains trains dépassent les 200km/h, tandis que d’autres vont plutôt à 70km/h. Quels sont ces trains plus lent? La variable <code>type</code> codifie probablement ce fait, et permet de voir que ce sont les trains RegioExpress qui sont dans cette catégorie.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro.html#cb13-1" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="intro.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(duree <span class="sc">&gt;</span> <span class="dv">200</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="intro.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type, dest) <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="intro.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">&quot;durée moyenne&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(duree), </span>
<span id="cb13-5"><a href="intro.html#cb13-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;écart-type&quot;</span> <span class="ot">=</span> <span class="fu">sd</span>(duree),</span>
<span id="cb13-6"><a href="intro.html#cb13-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;prix moyen&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(prix), </span>
<span id="cb13-7"><a href="intro.html#cb13-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;écart-type&quot;</span> <span class="ot">=</span> <span class="fu">sd</span>(prix)) </span></code></pre></div>
<pre><code>##       type             dest durée moyenne écart-type prix moyen écart-type
## 1 REXPRESS Barcelone-Madrid           544          0       43.2          0
## 2 REXPRESS Madrid-Barcelone           562          0       43.2          0</code></pre>
<p>Aller de Madrid à Barcelone à l’aide d’un train régulier prend 18 minutes de plus. Avec plus de 9h de trajet, pas étonnant donc que ces billets soient peu courus. Encore plus frappant, on note que le prix des billets est fixe: 43.25 euros peu importe que le trajet soit aller ou retour. C’est probablement la trouvaille la plus importante jusqu’à maintenant, car les billets de train de type RegioExpress ne forment pas un échantillon: il n’y a aucune variabilité! On aurait pu également découvrir cette anomalie en traçant une boîte à moustaches du prix en fonction du type de train.</p>
<div class="figure" style="text-align: center"><span id="fig:renfe-aed4"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/renfe-aed4-1.png" alt="Boîte à moustaches du prix de billets de train de Renfe en fonction de la destination et du type de train." width="70%" />
<p class="caption">
Figure 1.13: Boîte à moustaches du prix de billets de train de Renfe en fonction de la destination et du type de train.
</p>
</div>
<p>On pourrait soupçonner que les trains étiquetés <code>AVE</code> soient plus rapides, sachant que c’est l’acronyme de <em>Alta Velocidad Española</em>, littéralement haute vitesse espagnole. Qu’en est-il des distinctions entre les deux types de trains étiquetés AVE? Selon <a href="https://www.renfe-sncf.com/rw-en/services/a-unique-experience/Pages/services.aspx">le site de la SNCF</a>, les trains AVE-TGV sont des partenariats entre la Renfe et la SNCF et effectuent des liaisons entre la France et l’Espagne.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro.html#cb15-1" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="intro.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(type <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;AVE&quot;</span>,<span class="st">&quot;AVE-TGV&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="intro.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(type, dest) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="intro.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">&quot;durée moyenne&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(duree), </span>
<span id="cb15-5"><a href="intro.html#cb15-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;écart-type&quot;</span> <span class="ot">=</span> <span class="fu">sd</span>(duree),</span>
<span id="cb15-6"><a href="intro.html#cb15-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;prix moyen&quot;</span> <span class="ot">=</span> <span class="fu">mean</span>(prix),</span>
<span id="cb15-7"><a href="intro.html#cb15-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;écart-type&quot;</span> <span class="ot">=</span> <span class="fu">sd</span>(prix))</span></code></pre></div>
<pre><code>##      type             dest durée moyenne écart-type prix moyen écart-type
## 1     AVE Barcelone-Madrid           171       15.9       87.4       19.8
## 2     AVE Madrid-Barcelone           170       16.6       88.2       20.8
## 3 AVE-TGV Barcelone-Madrid           175        0.0       87.0       16.8
## 4 AVE-TGV Madrid-Barcelone           179        0.0       90.6       20.2</code></pre>
<p>Les prix sont beaucoup plus élevés, en moyenne plus de deux fois plus que les trains régionaux. Les écarts de prix importants (l’écart type est de 20 euros) indique qu’il y a peut-être d’autres sources d’hétérogénéité, mais on pourrait soupçonner que la Renfe pratique la tarification dynamique. Il y un seul temps de parcours prévu pour les trains AVE-TGV. On ne note pas de différence de prix notable selon la direction ou le type de train grande vitesse, mais peut-être que les tarifs ou la classe disponibles diffèrent selon que le train ou non est en partenariat avec la compagnie française.</p>
<p>On a pas encore considéré le tarif et la classe des billets, hormis pour les trains RegioExpress. On voit dans la Figure <a href="intro.html#fig:renfe-aed7">1.15</a> une forte différente dans l’hétérogénéité des prix selon le tarif; le tarif Promo prend plusieurs valeurs distinctes, tandis que les tarifs AdultoIda et Flexible semblent ne prendre que quelques valeurs. La première classe (<code>Preferente</code>) est plus chère et il y a moins d’observations dans ce groupe. La classe Turista est la classe la moins dispendieuse et la plus populaire. <a href="http://web.archive.org/web/20161111134241/http://www.renfe.com/viajeros/tarifas/billete_promo.html"><code>TuristaPlus</code></a> offre plus de confort, tandis que <code>TuristaSolo</code> permet d’obtenir un siège individuel.</p>
<p>Côté tarif, <a href="http://web.archive.org/web/20161111134241/http://www.renfe.com/viajeros/tarifas/billete_promo.html">Promo</a> et <a href="http://web.archive.org/web/20161110220249/http://www.renfe.com/viajeros/tarifas/billete_promoplus.html">PromoPlus</a> permette d’obtenir des rabais pouvant aller jusqu’à respectivement 70% et 65%. Les annulations et changements ne sont pas possibles avec Promo, mais disponibles avec PromoPlus moyennant une pénalité équivalent à 30-20% du prix du billet. Le tarif <a href="http://web.archive.org/web/20161108192609/http://www.renfe.com/viajeros/tarifas/billete_flexible.html">Flexible</a> est disponible au même prix que les billets réguliers, avec des bénéfices additionnels.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> <span class="fu">subset</span>(tarif  <span class="sc">!=</span> <span class="st">&quot;AdultoIda&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="intro.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> prix, <span class="at">x =</span> classe, <span class="at">col =</span> tarif)) <span class="sc">+</span> </span>
<span id="cb17-3"><a href="intro.html#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb17-4"><a href="intro.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;prix (en euros)&quot;</span>,</span>
<span id="cb17-5"><a href="intro.html#cb17-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;classe&quot;</span>,</span>
<span id="cb17-6"><a href="intro.html#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;tarif&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="intro.html#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:renfe-aed6"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/renfe-aed6-1.png" alt="Boîte à moustaches du prix en fonction du tarif et de la classe de billets de trains à haute vitesse de la Renfe." width="70%" />
<p class="caption">
Figure 1.14: Boîte à moustaches du prix en fonction du tarif et de la classe de billets de trains à haute vitesse de la Renfe.
</p>
</div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="intro.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> renfe, <span class="fu">aes</span>(<span class="at">x =</span> prix, <span class="at">y=</span>..density.., <span class="at">fill =</span> tarif)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="intro.html#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="intro.html#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;prix (en euros)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;densité&quot;</span>) <span class="sc">+</span> </span>
<span id="cb18-4"><a href="intro.html#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:renfe-aed7"></span>
<img src="MATH60604_Modelisation_statistique_files/figure-html/renfe-aed7-1.png" alt="Histogrammes du prix en fonction du tarif de billets de trains de la Renfe." width="70%" />
<p class="caption">
Figure 1.15: Histogrammes du prix en fonction du tarif de billets de trains de la Renfe.
</p>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="intro.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vérifier la répartition des billets Flexible</span></span>
<span id="cb19-2"><a href="intro.html#cb19-2" aria-hidden="true" tabindex="-1"></a>renfe <span class="sc">%&gt;%</span> <span class="fu">subset</span>(tarif  <span class="sc">==</span> <span class="st">&quot;Flexible&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">count</span>(prix, classe)</span></code></pre></div>
<pre><code>##   prix      classe    n
## 1  108     Turista 1050
## 2  108 TuristaSolo   67
## 3  127     Turista  285
## 4  127 TuristaSolo    9
## 5  129 TuristaPlus   31
## 6  140  Preferente    2
## 7  152 TuristaPlus   10
## 8  182  Preferente   78
## 9  214  Preferente   12</code></pre>
<p>On note que la répartition des prix pour les billets de classe Flexible est inhabituelle: notre boîte à moustachesest écrasée et l’écart interquartile semble nul, même si quelques valeurs inexpliquées sont aussi présentes. L’écrasante majorité des billets Flexibles sont en classe Turista, donc ça pourrait être dû à un (trop) faible nombre de billets dans chaque catégorie. On peut rejeter cette hypothèse en calculant le nombre de trains au tarif Flexible pour les différents types de billets. Ni la durée, ni le type de train, ni la destination n’expliquent pas pourquoi le prix de certains billets Flexibles est plus faible ou élevés. Le prix des billets Promo est plus faible, et les billets au tarif Preferente (la première classe) sont plus élevés.</p>
<p>On peut résumer notre brève analyse exploratoire:</p>
<ul>
<li>plus de 91% des trains sont des trains à grande vitesse AVE.</li>
<li>le temps de trajet dépend du type de train: les trains à grande vitesse mettent 3h20 au maximum pour relier Madrid et Barcelone.</li>
<li>les temps de trajets sont ceux annoncés (variable discrète avec 17 valeurs uniques, dont 13 pour les trains AVE)</li>
<li>le prix de trains RegioExpress est fixe (43.25€); tous ces billets sont dans la classe Turista et au tarif Adulto Ida. 57% de ces trains vont de Barcelone à Madrid. La durée du trajet pour les RegioExpress est de 9h22 de Barcelona à Madrid, 18 minutes de plus que dans l’autre direction.</li>
<li>les billets en classe<code>Preferente</code> sont plus chers et moins fréquents. La classe <code>Turista</code> est la classe la moins dispendieuse et la plus populaire. <code>TuristaPlus</code> offre plus de confort, tandis que <code>TuristaSolo</code> permet d’obtenir un siège individuel.</li>
<li>selon le <a href="https://www.renfe.com/es/es/viajar/tarifas/billetes.html">site web de la Renfe</a>, les billets au tarif <code>Flexible</code> « viennent avec des offres additionnelles qui permettent au passagers d’échanger leurs billets ou annuler s’ils manquent leurs trains. »; en contrepartie, ces billets sont plus chers et leur tarif est fixe sauf une poignée de billets dont le prix reste inexpliqué.</li>
<li>la distribution des prix des billets de TGV au tarif <code>Promo</code> est plus ou moins symmétrique, tandis que les billets au tarif <code>Flexible</code> apparaissent tronqués à gauche (le prix minimum pour ces billets est 107.7€ dans l’échantillon).</li>
<li>la Renfe pratique la tarification dynamique pour les billets au tarif promotionnel <code>Promo</code>: ces derniers peuvent être jusqu’à 70% moins chers que les billets à prix régulier lorsqu’achetés via l’agence officielle ou le site de Renfe. Ces billets ne peuvent être ni remboursés, ni échangés.</li>
<li>il n’y a pas d’indication à effet de quoi les prix varient selon la direction du trajet.</li>
</ul>
<!-- ```{r} -->
<!-- knitr::include_url("https://www.youtube.com/embed/9bZkp7q19f0") -->
<!-- ``` -->

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression-lineaire.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MATH60604_Modelisation_statistique.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
